---
- name: install jenkins
  hosts: all
  become: true
  gather_facts: no

  tasks: 
  - name: install java
    yum: 
      name: java-1.8.0-openjdk
      state: installed


  - name: installed wget
    yum:
      name: wget
      state: installed 

  - name: download jenkins packages
    get_url:  
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: adding jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key


  - name: installed jenkins
    yum:
      name: jenkins
      state: installed                   

  - name: start the services
    service: 
      name: jenkins
      state: started
      enabled: yes

  - name: Ensure jenkins service added to firewalld
    firewalld: 
      service: jenkins
      state: enabled
      permanent: yes
      immediate: yes

  - name: Ensure port 8080 added to firewalld
    firewalld:
      port: 8080/tcp
      state: enabled
      permanent: yes
      immediate: yes              