---
- name: Install multiple packages in FOR Loops
  hosts: all
  become: true
  gather_facts: yes



  tasks:
  - name: install and delete through FOR loop
    yum:
     name: "{{ item.pkg }}"
     state: "{{ item.setup }}"

    loop:
     - { pkg: 'git', setup: 'installed' }
     - { pkg: 'make', setup: 'latest' }
     - { pkg: 'wget', setup: 'removed' }
     - { pkg: 'tree', setup: 'absent' }